#CI项目
name: QCA-ALL

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:   输入:
      PACKAGE:   包:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false   假
        type: string   类型:字符串
      TEST:   测试:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'   默认值:“假”
        required: false   假
        type: boolean   类型:布尔

#CI权限
permissions: write-all   权限:编写所有

#CI任务
jobs:   工作:
  config:   配置:
    name: ${{matrix.CONFIG}}   名称:${{矩阵。配置}}
    strategy:   策略:
      fail-fast: false   假
      #max-parallel: 3
      matrix:   矩阵:
        CONFIG: [IPQ60XX-WIFI-YES, IPQ60XX-WIFI-NO, IPQ807X-WIFI-YES, IPQ807X-WIFI-NO]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: aurora
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名称
      WRT_SSID: OWRT
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 192.168.2.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
